name: musca.se
gems:
  - jekyll-feed
markdown: kramdown
highlighter: pygments
description: "This is where I keep a blog about my github projects, web design & development."
url: http://musca.se
excerpt_separator: <!--more-->
exclude: ["src", "node_modules", "gulpfile.js", "package.json", "README.md"]
production_url : http://musca.se
